version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spendsmart
      MYSQL_USER: spendsmartuser
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      start_period: 10s

  backend:
    container_name: nodeappcontainer
    build: ./backend
    image: moteshubham/spendsmart-backend:v1
    options: --user root
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - DATABASE_URL=mysql://spendsmartuser:password@mysql:3306/spendsmart
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app

volumes:
  mysql-data:
