name: CICD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Compose services
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Deploy to EC2
        runs-on: aws-ec2
        steps:
          - name: Pull Docker Compose services
            run: docker-compose -f docker-compose.yml pull

          - name: Remove old containers
            run: docker-compose -f docker-compose.yml down

          - name: Deploy using Docker Compose
            run: docker-compose -f docker-compose.yml up -d