name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Compose services
        run: docker-compose -f docker-compose.yml build

      - name: Push Docker Compose services
        run: docker-compose -f docker-compose.yml push

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Pull Docker Compose services
        run: docker-compose -f docker-compose.yml pull

      - name: Remove old containers
        run: docker-compose -f docker-compose.yml down

      - name: Deploy using Docker Compose
        run: docker-compose -f docker-compose.yml up -d